import os

def folders():
    folder = folder_to_track()
    extensions_folders = {
    #No name
        'noname' : folder + "/Other/Uncategorized",
    #Audio
        '.aif' : folder + "/Media/Audio",
        '.cda' : folder + "/Media/Audio",
        '.mid' : folder + "/Media/Audio",
        '.midi' : folder + "/Media/Audio",
        '.mp3' : folder + "/Media/Audio",
        '.mpa' : folder + "/Media/Audio",
        '.ogg' : folder + "/Media/Audio",
        '.wav' : folder + "/Media/Audio",
        '.wma' : folder + "/Media/Audio",
        '.wpl' : folder + "/Media/Audio",
        '.m3u' : folder + "/Media/Audio",
    #Text
        '.txt' : folder + "/Text/TextFiles",
        '.doc' : folder + "/Text/Microsoft/Word",
        '.docx' : folder + "/Text/Microsoft/Word",
        '.odt ' : folder + "/Text/TextFiles",
        '.pdf': folder + "/Text/PDF",
        '.rtf': folder + "/Text/TextFiles",
        '.tex': folder + "/Text/TextFiles",
        '.wks ': folder + "/Text/TextFiles",
        '.wps': folder + "/Text/TextFiles",
        '.wpd': folder + "/Text/TextFiles",
    #Video
        '.3g2': folder + "/Media/Video",
        '.3gp': folder + "/Media/Video",
        '.avi': folder + "/Media/Video",
        '.flv': folder + "/Media/Video",
        '.h264': folder + "/Media/Video",
        '.m4v': folder + "/Media/Video",
        '.mkv': folder + "/Media/Video",
        '.mov': folder + "/Media/Video",
        '.mp4': folder + "/Media/Video",
        '.mpg': folder + "/Media/Video",
        '.mpeg': folder + "/Media/Video",
        '.rm': folder + "/Media/Video",
        '.swf': folder + "/Media/Video",
        '.vob': folder + "/Media/Video",
        '.wmv': folder + "/Media/Video",
    #Images
        '.ai': folder + "/Media/Images",
        '.bmp': folder + "/Media/Images",
        '.gif': folder + "/Media/Images",
        '.ico': folder + "/Media/Images",
        '.jpg': folder + "/Media/Images",
        '.jpeg': folder + "/Media/Images",
        '.png': folder + "/Media/Images",
        '.ps': folder + "/Media/Images",
        '.psd': folder + "/Media/Images",
        '.svg': folder + "/Media/Images",
        '.tif': folder + "/Media/Images",
        '.tiff': folder + "/Media/Images",
        '.CR2': folder + "/Media/Images",
    #Internet
        '.asp': folder + "/Other/Internet",
        '.aspx': folder + "/Other/Internet",
        '.cer': folder + "/Other/Internet",
        '.cfm': folder + "/Other/Internet",
        '.cgi': folder + "/Other/Internet",
        '.pl': folder + "/Other/Internet",
        '.css': folder + "/Other/Internet",
        '.htm': folder + "/Other/Internet",
        '.js': folder + "/Other/Internet",
        '.jsp': folder + "/Other/Internet",
        '.part': folder + "/Other/Internet",
        '.php': folder + "/Other/Internet",
        '.rss': folder + "/Other/Internet",
        '.xhtml': folder + "/Other/Internet",
    #Compressed
        '.7z': folder + "/Other/Compressed",
        '.arj': folder + "/Other/Compressed",
        '.deb': folder + "/Other/Compressed",
        '.pkg': folder + "/Other/Compressed",
        '.rar': folder + "/Other/Compressed",
        '.rpm': folder + "/Other/Compressed",
        '.tar.gz': folder + "/Other/Compressed",
        '.z': folder + "/Other/Compressed",
        '.zip': folder + "/Other/Compressed",
    #Disc
        '.bin': folder + "/Other/Disc",
        '.dmg': folder + "/Other/Disc",
        '.iso': folder + "/Other/Disc",
        '.toast': folder + "/Other/Disc",
        '.vcd': folder + "/Other/Disc",
    #Data
        '.csv': folder + "/Programming/Database",
        '.dat': folder + "/Programming/Database",
        '.db': folder + "/Programming/Database",
        '.dbf': folder + "/Programming/Database",
        '.log': folder + "/Programming/Database",
        '.mdb': folder + "/Programming/Database",
        '.sav': folder + "/Programming/Database",
        '.sql': folder + "/Programming/Database",
        '.tar': folder + "/Programming/Database",
        '.xml': folder + "/Programming/Database",
        '.json': folder + "/Programming/Database",
    #Executables
        '.apk': folder + "/Other/Executables",
        '.bat': folder + "/Other/Executables",
        '.com': folder + "/Other/Executables",
        '.exe': folder + "/Other/Executables",
        '.gadget': folder + "/Other/Executables",
        '.jar': folder + "/Other/Executables",
        '.wsf': folder + "/Other/Executables",
    #Fonts
        '.fnt': folder + "/Other/Fonts",
        '.fon': folder + "/Other/Fonts",
        '.otf': folder + "/Other/Fonts",
        '.ttf': folder + "/Other/Fonts",
    #Presentations
        '.key': folder + "/Text/Presentations",
        '.odp': folder + "/Text/Presentations",
        '.pps': folder + "/Text/Presentations",
        '.ppt': folder + "/Text/Presentations",
        '.pptx': folder + "/Text/Presentations",
    #Programming
        '.c': folder + "/Programming/C&C++",
        '.class': folder + "/Programming/Java",
        '.dart': folder + "/Programming/Dart",
        '.py': folder + "/Programming/Python",
        '.sh': folder + "/Programming/Shell",
        '.swift': folder + "/Programming/Swift",
        '.html': folder + "/Programming/C&C++",
        '.h': folder + "/Programming/C&C++",
    #Spreadsheets
        '.ods' : folder + "/Text/Microsoft/Excel",
        '.xlr' : folder + "/Text/Microsoft/Excel",
        '.xls' : folder + "/Text/Microsoft/Excel",
        '.xlsx' : folder + "/Text/Microsoft/Excel",
    #System
        '.bak' : folder + "/Text/Other/System",
        '.cab' : folder + "/Text/Other/System",
        '.cfg' : folder + "/Text/Other/System",
        '.cpl' : folder + "/Text/Other/System",
        '.cur' : folder + "/Text/Other/System",
        '.dll' : folder + "/Text/Other/System",
        '.dmp' : folder + "/Text/Other/System",
        '.drv' : folder + "/Text/Other/System",
        '.icns' : folder + "/Text/Other/System",
        '.ini' : folder + "/Text/Other/System",
        '.lnk' : folder + "/Text/Other/System",
        '.msi' : folder + "/Text/Other/System",
        '.sys' : folder + "/Text/Other/System",
        '.tmp' : folder + "/Text/Other/System",
    }
    return extensions_folders

def folder_to_track():
    folder = r'D:\Users\Levy\Downloads'
    return folder
    
    